INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (1, 1, 0, 0, 1, '/var/www/html/data/maths/Chapter_1/exemple_1.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (2, 2, 0, 0, 1, '/var/www/html/data/maths/Chapter_1/exemple_2.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (3, 3, 0, 0, 1, '/var/www/html/data/maths/Chapter_1/exemple_3.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (4, 4, 0, 0, 1, '/var/www/html/data/maths/Chapter_1/exemple_4.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (5, 5, 0, 0, 1, '/var/www/html/data/maths/Chapter_1/exemple_5.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (6, 6, 0, 0, 1, '/var/www/html/data/maths/Chapter_1/exemple_6.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (7, 11, 0, 0, 2, '/var/www/html/data/maths/Chapter_2/exemple_11.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (8, 12, 0, 0, 2, '/var/www/html/data/maths/Chapter_2/exemple_12.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (9, 6, 0, 0, 2, '/var/www/html/data/maths/Chapter_2/exemple_6.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (10, 8, 0, 0, 2, '/var/www/html/data/maths/Chapter_2/exemple_8.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (11, 9, 0, 0, 2, '/var/www/html/data/maths/Chapter_2/exemple_9.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (12, 12, 0, 0, 6, '/var/www/html/data/maths/Chapter_6/exemple_12.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (13, 6, 0, 0, 6, '/var/www/html/data/maths/Chapter_6/exemple_6.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (14, 8, 0, 0, 6, '/var/www/html/data/maths/Chapter_6/exemple_8.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (15, 11, 0, 0, 7, '/var/www/html/data/maths/Chapter_7/exemple_11.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (16, 12, 0, 0, 7, '/var/www/html/data/maths/Chapter_7/exemple_12.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (17, 13, 0, 0, 7, '/var/www/html/data/maths/Chapter_7/exemple_13.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (18, 17, 0, 0, 7, '/var/www/html/data/maths/Chapter_7/exemple_17.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (19, 4, 0, 0, 7, '/var/www/html/data/maths/Chapter_7/exemple_4.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (20, 9, 0, 0, 7, '/var/www/html/data/maths/Chapter_7/exemple_9.html')
INSERT INTO examples (examples_id, examples_number, examples_is_bac, examples_is_ds, examples_chapter_id, examples_path)
    VALUES (21, 6, 0, 0, 8, '/var/www/html/data/maths/Chapter_8/exemple_6.html')
